#!/bin/bash
# This script will help organize the refactoring
echo "Creating module structure for redstr..."
echo ""
echo "Modules to create:"
echo "  ✓ src/rng.rs (created)"
echo "  ✓ src/transformations/encoding.rs (created)"
echo "  - src/transformations/case.rs"
echo "  - src/transformations/unicode.rs"
echo "  - src/transformations/injection.rs"
echo "  - src/transformations/obfuscation.rs"
echo "  - src/transformations/phishing.rs"
echo "  - src/transformations/bot_detection.rs"
echo "  - src/transformations/web_security.rs"
echo "  - src/transformations/shell.rs"
echo "  - src/transformations/mod.rs"
echo "  - src/builder.rs"
echo ""
echo "Then update src/lib.rs to use modules and re-export everything"
