"""
Type stubs for redstr Python bindings
"""

__version__: str

# Case transformations
def alternate_case(text: str) -> str: ...
def case_swap(text: str) -> str: ...
def inverse_case(text: str) -> str: ...
def randomize_capitalization(text: str) -> str: ...
def to_camel_case(text: str) -> str: ...
def to_kebab_case(text: str) -> str: ...
def to_snake_case(text: str) -> str: ...

# Encoding transformations
def base64_encode(text: str) -> str: ...
def hex_encode(text: str) -> str: ...
def hex_encode_mixed(text: str) -> str: ...
def html_entity_encode(text: str) -> str: ...
def mixed_encoding(text: str) -> str: ...
def url_encode(text: str) -> str: ...

# Unicode transformations
def homoglyph_substitution(text: str) -> str: ...
def space_variants(text: str) -> str: ...
def unicode_normalize_variants(text: str) -> str: ...
def unicode_variations(text: str) -> str: ...
def zalgo_text(text: str) -> str: ...

# Injection transformations
def command_injection(text: str) -> str: ...
def couchdb_injection(text: str) -> str: ...
def dynamodb_obfuscate(text: str) -> str: ...
def mongodb_injection(text: str) -> str: ...
def nosql_operator_injection(text: str) -> str: ...
def null_byte_injection(text: str) -> str: ...
def path_traversal(text: str) -> str: ...
def sql_comment_injection(text: str) -> str: ...
def ssti_framework_variation(template: str, framework: str) -> str: ...
def ssti_injection(text: str) -> str: ...
def ssti_syntax_obfuscate(text: str) -> str: ...
def xss_tag_variations(text: str) -> str: ...

# Obfuscation transformations
def double_characters(text: str) -> str: ...
def js_string_concat(text: str) -> str: ...
def leetspeak(text: str) -> str: ...
def reverse_string(text: str) -> str: ...
def rot13(text: str) -> str: ...
def vowel_swap(text: str) -> str: ...
def whitespace_padding(text: str) -> str: ...

# Phishing transformations
def advanced_domain_spoof(text: str) -> str: ...
def domain_typosquat(text: str) -> str: ...
def email_obfuscation(text: str) -> str: ...
def url_shortening_pattern(text: str) -> str: ...

# Bot detection transformations
def accept_language_variation(text: str) -> str: ...
def cloudflare_challenge_variation(text: str) -> str: ...
def http2_header_order(text: str) -> str: ...
def random_user_agent() -> str: ...
def tls_fingerprint_variation(text: str) -> str: ...

# Cloudflare transformations
def canvas_fingerprint_variation(text: str) -> str: ...
def cloudflare_challenge_response(text: str) -> str: ...
def cloudflare_turnstile_variation(text: str) -> str: ...
def font_fingerprint_consistency(text: str) -> str: ...
def tls_handshake_pattern(text: str) -> str: ...
def webgl_fingerprint_obfuscate(text: str) -> str: ...

# Shell transformations
def bash_obfuscate(text: str) -> str: ...
def env_var_obfuscate(text: str) -> str: ...
def file_path_obfuscate(text: str) -> str: ...
def powershell_obfuscate(text: str) -> str: ...

# Web security transformations
def api_endpoint_variation(text: str) -> str: ...
def graphql_introspection_bypass(text: str) -> str: ...
def graphql_obfuscate(text: str) -> str: ...
def graphql_variable_injection(text: str) -> str: ...
def http_header_variation(text: str) -> str: ...
def jwt_algorithm_confusion(text: str) -> str: ...
def jwt_header_manipulation(text: str) -> str: ...
def jwt_payload_obfuscate(text: str) -> str: ...
def jwt_signature_bypass(text: str) -> str: ...
def session_token_variation(text: str) -> str: ...

# Builder class
class TransformBuilder:
    """
    Builder for chaining multiple transformations.
    
    Example:
        >>> builder = TransformBuilder("hello world")
        >>> result = builder.leetspeak().base64().build()
    """
    def __init__(self, text: str) -> None: ...
    def alternate_case(self) -> "TransformBuilder": ...
    def case_swap(self) -> "TransformBuilder": ...
    def inverse_case(self) -> "TransformBuilder": ...
    def randomize_capitalization(self) -> "TransformBuilder": ...
    def camel_case(self) -> "TransformBuilder": ...
    def kebab_case(self) -> "TransformBuilder": ...
    def snake_case(self) -> "TransformBuilder": ...
    def base64(self) -> "TransformBuilder": ...
    def hex(self) -> "TransformBuilder": ...
    def url(self) -> "TransformBuilder": ...
    def leetspeak(self) -> "TransformBuilder": ...
    def rot13(self) -> "TransformBuilder": ...
    def reverse(self) -> "TransformBuilder": ...
    def build(self) -> str: ...
