/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function randomizeCapitalization(input: string): string
export declare function alternateCase(input: string): string
export declare function caseSwap(input: string): string
export declare function inverseCase(input: string): string
export declare function toCamelCase(input: string): string
export declare function toSnakeCase(input: string): string
export declare function toKebabCase(input: string): string
export declare function base64Encode(input: string): string
export declare function urlEncode(input: string): string
export declare function hexEncode(input: string): string
export declare function hexEncodeMixed(input: string): string
export declare function htmlEntityEncode(input: string): string
export declare function mixedEncoding(input: string): string
export declare function homoglyphSubstitution(input: string): string
export declare function unicodeVariations(input: string): string
export declare function zalgoText(input: string): string
export declare function spaceVariants(input: string): string
export declare function unicodeNormalizeVariants(input: string): string
export declare function sqlCommentInjection(input: string): string
export declare function xssTagVariations(input: string): string
export declare function nullByteInjection(input: string): string
export declare function pathTraversal(input: string): string
export declare function commandInjection(input: string): string
export declare function mongodbInjection(input: string): string
export declare function couchdbInjection(input: string): string
export declare function dynamodbObfuscate(input: string): string
export declare function nosqlOperatorInjection(input: string): string
export declare function sstiInjection(input: string): string
export declare function sstiFrameworkVariation(template: string, framework: string): string
export declare function sstiSyntaxObfuscate(input: string): string
export declare function leetspeak(input: string): string
export declare function rot13(input: string): string
export declare function vowelSwap(input: string): string
export declare function doubleCharacters(input: string): string
export declare function reverseString(input: string): string
export declare function whitespacePadding(input: string): string
export declare function jsStringConcat(input: string): string
export declare function domainTyposquat(input: string): string
export declare function advancedDomainSpoof(input: string): string
export declare function emailObfuscation(input: string): string
export declare function urlShorteningPattern(input: string): string
export declare function randomUserAgent(): string
export declare function tlsFingerprintVariation(input: string): string
export declare function http2HeaderOrder(input: string): string
export declare function acceptLanguageVariation(input: string): string
export declare function cloudflareChallengeVariation(input: string): string
export declare function cloudflareTurnstileVariation(input: string): string
export declare function cloudflareChallengeResponse(input: string): string
export declare function tlsHandshakePattern(input: string): string
export declare function canvasFingerprintVariation(input: string): string
export declare function webglFingerprintObfuscate(input: string): string
export declare function fontFingerprintConsistency(input: string): string
export declare function httpHeaderVariation(input: string): string
export declare function apiEndpointVariation(input: string): string
export declare function graphqlObfuscate(input: string): string
export declare function sessionTokenVariation(input: string): string
export declare function graphqlVariableInjection(input: string): string
export declare function graphqlIntrospectionBypass(input: string): string
export declare function jwtHeaderManipulation(input: string): string
export declare function jwtPayloadObfuscate(input: string): string
export declare function jwtAlgorithmConfusion(input: string): string
export declare function jwtSignatureBypass(input: string): string
export declare function powershellObfuscate(input: string): string
export declare function bashObfuscate(input: string): string
export declare function envVarObfuscate(input: string): string
export declare function filePathObfuscate(input: string): string
