/* auto-generated by NAPI-RS */
/* eslint-disable */

/**
 * redstr - Native string transformations for security testing
 * 
 * This module provides high-performance string transformation functions
 * for security testing, including WAF bypass, XSS, SQL injection,
 * phishing detection, and evasion testing.
 */

// ============================================================================
// Case Transformations
// ============================================================================

/** Randomize the capitalization of each character. */
export function randomizeCapitalization(input: string): string;

/** Swap the case of each character. */
export function caseSwap(input: string): string;

/** Alternate case for each character. */
export function alternateCase(input: string): string;

/** Inverse case transformation. */
export function inverseCase(input: string): string;

/** Convert to camelCase. */
export function toCamelCase(input: string): string;

/** Convert to snake_case. */
export function toSnakeCase(input: string): string;

/** Convert to kebab-case. */
export function toKebabCase(input: string): string;

// ============================================================================
// Encoding Transformations
// ============================================================================

/** Encode string to Base64. */
export function base64Encode(input: string): string;

/** URL encode a string. */
export function urlEncode(input: string): string;

/** Hex encode a string. */
export function hexEncode(input: string): string;

/** Hex encode with mixed case. */
export function hexEncodeMixed(input: string): string;

/** HTML entity encode a string. */
export function htmlEntityEncode(input: string): string;

/** Apply mixed encoding. */
export function mixedEncoding(input: string): string;

// ============================================================================
// Obfuscation Transformations
// ============================================================================

/** Apply leetspeak transformation. */
export function leetspeak(input: string): string;

/** Apply ROT13 cipher. */
export function rot13(input: string): string;

/** Reverse a string. */
export function reverseString(input: string): string;

/** Double each character in the string. */
export function doubleCharacters(input: string): string;

/** Swap vowels in the string. */
export function vowelSwap(input: string): string;

/** Add whitespace padding. */
export function whitespacePadding(input: string): string;

/** JavaScript string concatenation obfuscation. */
export function jsStringConcat(input: string): string;

// ============================================================================
// Unicode Transformations
// ============================================================================

/** Apply homoglyph substitution. */
export function homoglyphSubstitution(input: string): string;

/** Apply zalgo text effect. */
export function zalgoText(input: string): string;

/** Apply Unicode variations. */
export function unicodeVariations(input: string): string;

/** Apply space variants. */
export function spaceVariants(input: string): string;

/** Apply Unicode normalization variants. */
export function unicodeNormalizeVariants(input: string): string;

// ============================================================================
// Phishing Transformations
// ============================================================================

/** Generate typosquatted domain. */
export function domainTyposquat(input: string): string;

/** Obfuscate email address. */
export function emailObfuscation(input: string): string;

/** Generate URL shortening pattern. */
export function urlShorteningPattern(input: string): string;

/** Advanced domain spoofing. */
export function advancedDomainSpoof(input: string): string;

// ============================================================================
// Injection Transformations
// ============================================================================

/** Apply XSS tag variations. */
export function xssTagVariations(input: string): string;

/** Apply SQL comment injection. */
export function sqlCommentInjection(input: string): string;

/** Apply command injection patterns. */
export function commandInjection(input: string): string;

/** Apply path traversal patterns. */
export function pathTraversal(input: string): string;

/** Apply null byte injection. */
export function nullByteInjection(input: string): string;

/** Apply SSTI injection. */
export function sstiInjection(input: string): string;

/** Apply MongoDB injection. */
export function mongodbInjection(input: string): string;

// ============================================================================
// Bot Detection Transformations
// ============================================================================

/** Generate a random user agent string. */
export function randomUserAgent(): string;

/** Generate TLS fingerprint variation. */
export function tlsFingerprintVariation(input: string): string;

/** Generate accept language variation. */
export function acceptLanguageVariation(input: string): string;

// ============================================================================
// Shell Transformations
// ============================================================================

/** Obfuscate PowerShell command. */
export function powershellObfuscate(input: string): string;

/** Obfuscate Bash command. */
export function bashObfuscate(input: string): string;

/** Obfuscate environment variable. */
export function envVarObfuscate(input: string): string;

/** Obfuscate file path. */
export function filePathObfuscate(input: string): string;

// ============================================================================
// Web Security Transformations
// ============================================================================

/** GraphQL query obfuscation. */
export function graphqlObfuscate(input: string): string;

/** JWT header manipulation. */
export function jwtHeaderManipulation(input: string): string;

/** JWT payload obfuscation. */
export function jwtPayloadObfuscate(input: string): string;

// ============================================================================
// TransformBuilder
// ============================================================================

/**
 * Builder for chaining multiple transformations.
 * 
 * @example
 * ```typescript
 * const payload = new TransformBuilder('<script>alert(1)</script>')
 *     .caseSwap()
 *     .urlEncode()
 *     .build();
 * ```
 */
export class TransformBuilder {
    /** Create a new TransformBuilder with the given input. */
    constructor(input: string);
    
    /** Apply leetspeak transformation. */
    leetspeak(): this;
    
    /** Apply Base64 encoding. */
    base64(): this;
    
    /** Apply URL encoding. */
    urlEncode(): this;
    
    /** Apply case swap. */
    caseSwap(): this;
    
    /** Apply ROT13. */
    rot13(): this;
    
    /** Apply hex encoding. */
    hexEncode(): this;
    
    /** Apply homoglyph substitution. */
    homoglyphs(): this;
    
    /** Reverse the string. */
    reverse(): this;
    
    /** Build and return the final transformed string. */
    build(): string;
}
