/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 10
  if (!process.report || typeof process.report.getReport !== 'function') {
    try {
      const lddPath = require('child_process').execSync('which ldd').toString().trim()
      return readFileSync(lddPath, 'utf8').includes('musl')
    } catch (e) {
      return true
    }
  } else {
    const { glibcVersionRuntime } = process.report.getReport().header
    return !glibcVersionRuntime
  }
}

switch (platform) {
  case 'android':
    switch (arch) {
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'redstr.android-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.android-arm64.node')
          } else {
            nativeBinding = require('redstr-android-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm':
        localFileExisted = existsSync(join(__dirname, 'redstr.android-arm-eabi.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.android-arm-eabi.node')
          } else {
            nativeBinding = require('redstr-android-arm-eabi')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Android ${arch}`)
    }
    break
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(
          join(__dirname, 'redstr.win32-x64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.win32-x64-msvc.node')
          } else {
            nativeBinding = require('redstr-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'ia32':
        localFileExisted = existsSync(
          join(__dirname, 'redstr.win32-ia32-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.win32-ia32-msvc.node')
          } else {
            nativeBinding = require('redstr-win32-ia32-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'redstr.win32-arm64-msvc.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.win32-arm64-msvc.node')
          } else {
            nativeBinding = require('redstr-win32-arm64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    localFileExisted = existsSync(join(__dirname, 'redstr.darwin-universal.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./redstr.darwin-universal.node')
      } else {
        nativeBinding = require('redstr-darwin-universal')
      }
      break
    } catch {}
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'redstr.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.darwin-x64.node')
          } else {
            nativeBinding = require('redstr-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(
          join(__dirname, 'redstr.darwin-arm64.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.darwin-arm64.node')
          } else {
            nativeBinding = require('redstr-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'freebsd':
    if (arch !== 'x64') {
      throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
    }
    localFileExisted = existsSync(join(__dirname, 'redstr.freebsd-x64.node'))
    try {
      if (localFileExisted) {
        nativeBinding = require('./redstr.freebsd-x64.node')
      } else {
        nativeBinding = require('redstr-freebsd-x64')
      }
    } catch (e) {
      loadError = e
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-x64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-x64-musl.node')
            } else {
              nativeBinding = require('redstr-linux-x64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-x64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-x64-gnu.node')
            } else {
              nativeBinding = require('redstr-linux-x64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-arm64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-arm64-musl.node')
            } else {
              nativeBinding = require('redstr-linux-arm64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-arm64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-arm64-gnu.node')
            } else {
              nativeBinding = require('redstr-linux-arm64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'arm':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-arm-musleabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-arm-musleabihf.node')
            } else {
              nativeBinding = require('redstr-linux-arm-musleabihf')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-arm-gnueabihf.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-arm-gnueabihf.node')
            } else {
              nativeBinding = require('redstr-linux-arm-gnueabihf')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 'riscv64':
        if (isMusl()) {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-riscv64-musl.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-riscv64-musl.node')
            } else {
              nativeBinding = require('redstr-linux-riscv64-musl')
            }
          } catch (e) {
            loadError = e
          }
        } else {
          localFileExisted = existsSync(
            join(__dirname, 'redstr.linux-riscv64-gnu.node')
          )
          try {
            if (localFileExisted) {
              nativeBinding = require('./redstr.linux-riscv64-gnu.node')
            } else {
              nativeBinding = require('redstr-linux-riscv64-gnu')
            }
          } catch (e) {
            loadError = e
          }
        }
        break
      case 's390x':
        localFileExisted = existsSync(
          join(__dirname, 'redstr.linux-s390x-gnu.node')
        )
        try {
          if (localFileExisted) {
            nativeBinding = require('./redstr.linux-s390x-gnu.node')
          } else {
            nativeBinding = require('redstr-linux-s390x-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

const { randomizeCapitalization, caseSwap, alternateCase, inverseCase, toCamelCase, toSnakeCase, toKebabCase, base64Encode, urlEncode, hexEncode, hexEncodeMixed, htmlEntityEncode, mixedEncoding, leetspeak, rot13, reverseString, doubleCharacters, vowelSwap, whitespacePadding, jsStringConcat, homoglyphSubstitution, zalgoText, unicodeVariations, spaceVariants, unicodeNormalizeVariants, domainTyposquat, emailObfuscation, urlShorteningPattern, advancedDomainSpoof, xssTagVariations, sqlCommentInjection, commandInjection, pathTraversal, nullByteInjection, sstiInjection, mongodbInjection, randomUserAgent, tlsFingerprintVariation, acceptLanguageVariation, powershellObfuscate, bashObfuscate, envVarObfuscate, filePathObfuscate, graphqlObfuscate, jwtHeaderManipulation, jwtPayloadObfuscate, TransformBuilder } = nativeBinding

module.exports.randomizeCapitalization = randomizeCapitalization
module.exports.caseSwap = caseSwap
module.exports.alternateCase = alternateCase
module.exports.inverseCase = inverseCase
module.exports.toCamelCase = toCamelCase
module.exports.toSnakeCase = toSnakeCase
module.exports.toKebabCase = toKebabCase
module.exports.base64Encode = base64Encode
module.exports.urlEncode = urlEncode
module.exports.hexEncode = hexEncode
module.exports.hexEncodeMixed = hexEncodeMixed
module.exports.htmlEntityEncode = htmlEntityEncode
module.exports.mixedEncoding = mixedEncoding
module.exports.leetspeak = leetspeak
module.exports.rot13 = rot13
module.exports.reverseString = reverseString
module.exports.doubleCharacters = doubleCharacters
module.exports.vowelSwap = vowelSwap
module.exports.whitespacePadding = whitespacePadding
module.exports.jsStringConcat = jsStringConcat
module.exports.homoglyphSubstitution = homoglyphSubstitution
module.exports.zalgoText = zalgoText
module.exports.unicodeVariations = unicodeVariations
module.exports.spaceVariants = spaceVariants
module.exports.unicodeNormalizeVariants = unicodeNormalizeVariants
module.exports.domainTyposquat = domainTyposquat
module.exports.emailObfuscation = emailObfuscation
module.exports.urlShorteningPattern = urlShorteningPattern
module.exports.advancedDomainSpoof = advancedDomainSpoof
module.exports.xssTagVariations = xssTagVariations
module.exports.sqlCommentInjection = sqlCommentInjection
module.exports.commandInjection = commandInjection
module.exports.pathTraversal = pathTraversal
module.exports.nullByteInjection = nullByteInjection
module.exports.sstiInjection = sstiInjection
module.exports.mongodbInjection = mongodbInjection
module.exports.randomUserAgent = randomUserAgent
module.exports.tlsFingerprintVariation = tlsFingerprintVariation
module.exports.acceptLanguageVariation = acceptLanguageVariation
module.exports.powershellObfuscate = powershellObfuscate
module.exports.bashObfuscate = bashObfuscate
module.exports.envVarObfuscate = envVarObfuscate
module.exports.filePathObfuscate = filePathObfuscate
module.exports.graphqlObfuscate = graphqlObfuscate
module.exports.jwtHeaderManipulation = jwtHeaderManipulation
module.exports.jwtPayloadObfuscate = jwtPayloadObfuscate
module.exports.TransformBuilder = TransformBuilder
