/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Randomize the capitalization of each character. */
export declare function randomizeCapitalization(input: string): string
/** Swap the case of each character. */
export declare function caseSwap(input: string): string
/** Alternate case for each character. */
export declare function alternateCase(input: string): string
/** Inverse case transformation. */
export declare function inverseCase(input: string): string
/** Convert to camelCase. */
export declare function toCamelCase(input: string): string
/** Convert to snake_case. */
export declare function toSnakeCase(input: string): string
/** Convert to kebab-case. */
export declare function toKebabCase(input: string): string
/** Encode string to Base64. */
export declare function base64Encode(input: string): string
/** URL encode a string. */
export declare function urlEncode(input: string): string
/** Hex encode a string. */
export declare function hexEncode(input: string): string
/** Hex encode with mixed case. */
export declare function hexEncodeMixed(input: string): string
/** HTML entity encode a string. */
export declare function htmlEntityEncode(input: string): string
/** Apply mixed encoding. */
export declare function mixedEncoding(input: string): string
/** Apply leetspeak transformation. */
export declare function leetspeak(input: string): string
/** Apply ROT13 cipher. */
export declare function rot13(input: string): string
/** Reverse a string. */
export declare function reverseString(input: string): string
/** Double each character in the string. */
export declare function doubleCharacters(input: string): string
/** Swap vowels in the string. */
export declare function vowelSwap(input: string): string
/** Add whitespace padding. */
export declare function whitespacePadding(input: string): string
/** JavaScript string concatenation obfuscation. */
export declare function jsStringConcat(input: string): string
/** Apply homoglyph substitution. */
export declare function homoglyphSubstitution(input: string): string
/** Apply zalgo text effect. */
export declare function zalgoText(input: string): string
/** Apply Unicode variations. */
export declare function unicodeVariations(input: string): string
/** Apply space variants. */
export declare function spaceVariants(input: string): string
/** Apply Unicode normalization variants. */
export declare function unicodeNormalizeVariants(input: string): string
/** Generate typosquatted domain. */
export declare function domainTyposquat(input: string): string
/** Obfuscate email address. */
export declare function emailObfuscation(input: string): string
/** Generate URL shortening pattern. */
export declare function urlShorteningPattern(input: string): string
/** Advanced domain spoofing. */
export declare function advancedDomainSpoof(input: string): string
/** Apply XSS tag variations. */
export declare function xssTagVariations(input: string): string
/** Apply SQL comment injection. */
export declare function sqlCommentInjection(input: string): string
/** Apply command injection patterns. */
export declare function commandInjection(input: string): string
/** Apply path traversal patterns. */
export declare function pathTraversal(input: string): string
/** Apply null byte injection. */
export declare function nullByteInjection(input: string): string
/** Apply SSTI injection. */
export declare function sstiInjection(input: string): string
/** Apply MongoDB injection. */
export declare function mongodbInjection(input: string): string
/** Generate a random user agent string. */
export declare function randomUserAgent(): string
/** Generate TLS fingerprint variation. */
export declare function tlsFingerprintVariation(input: string): string
/** Generate accept language variation. */
export declare function acceptLanguageVariation(input: string): string
/** Obfuscate PowerShell command. */
export declare function powershellObfuscate(input: string): string
/** Obfuscate Bash command. */
export declare function bashObfuscate(input: string): string
/** Obfuscate environment variable. */
export declare function envVarObfuscate(input: string): string
/** Obfuscate file path. */
export declare function filePathObfuscate(input: string): string
/** GraphQL query obfuscation. */
export declare function graphqlObfuscate(input: string): string
/** JWT header manipulation. */
export declare function jwtHeaderManipulation(input: string): string
/** JWT payload obfuscation. */
export declare function jwtPayloadObfuscate(input: string): string
/** Builder for chaining multiple transformations. */
export declare class TransformBuilder {
  /** Create a new TransformBuilder with the given input. */
  constructor(input: string)
  /** Apply leetspeak transformation. */
  leetspeak(): this
  /** Apply Base64 encoding. */
  base64(): this
  /** Apply URL encoding. */
  urlEncode(): this
  /** Apply case swap. */
  caseSwap(): this
  /** Apply ROT13. */
  rot13(): this
  /** Apply hex encoding. */
  hexEncode(): this
  /** Apply homoglyph substitution. */
  homoglyphs(): this
  /** Reverse the string. */
  reverse(): this
  /** Build and return the final transformed string. */
  build(): string
}
